# 【問題1】行列積を手計算する
AとBの行列積を手計算で解いてください。

計算過程もマークダウンテキストを用いて説明してください。

In [11]:
ans = np.array([[6, 29, -29], [12, 52, 38], [-18, -51, -48]])
ans

array([[  6,  29, -29],
       [ 12,  52,  38],
       [-18, -51, -48]])

計算手順は、a_ndarrayの各行とb_ndarrayの各列の積

答えをnp.array([[a, b, c], [d, e, f], [g, h, i]])とすると答えは下記。

$$a = -1*0 + 2*0 + 3*2$$
$$b = -1*2 + 2*2 + 3*9$$
$$c = -1*1 + 2*-8 + 3*-1$$
$$d = 4*0 - 5*0 + 6*2$$
$$e = 4*2 - 5*2 + 6*9$$
$$f = 4*1 - 5*-8 + 6*-1$$
$$g = 7*0 + 8*0 - 9*2$$
$$h = 7*2 + 8*2 - 9*9$$
$$i = 7*1 + 8*-8 - 9*-1$$

# 【問題2】NumPyの関数による計算
この行列積はNumPyのnp.matmul()やnp.dot()、または@演算子を使うことで簡単に計算できます。

これらを使い行列積を計算してください。

numpy.matmul — NumPy v1.16 Manual

numpy.dot — NumPy v1.16 Manual

In [9]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

a_ndarray.dot(b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

# 【問題3】ある要素の計算を実装
手計算をする際はまず行列Aの0行目と行列Bの0列目に注目し、以下の計算を行ったかと思います。

$・行列Aの(0,0)の要素 a_{0,0}と行列Bの(0,0)の要素b_{0,0}を掛け合わせる$
$・行列Aの(0,1)の要素a_{0,1}と行列Bの(1,0)の要素b_{1,0}を掛け合わせる$
$・行列Aの(0,2)の要素a_{0,2}と行列Bの(2,0)の要素b_{2,0}を掛け合わせる$
$・それらの値を全て足し合わせる$

数式で表すと
$$
\sum_{ k = 0 }^{ 2 } a_{0,k}b_{k,0}
$$
です。

この計算をnp.matmul()やnp.dot()、または@演算子を使わずに行うコードを書いてください。

In [65]:
ans_element = (a_ndarray[0, :]*b_ndarray[:, 0]).sum()
print(ans_element)

6


# 【問題4】行列積を行う関数の作成
問題3のコードを拡張し、行列積のスクラッチ実装を完成させてください。行列AとBを引数に受け取り、行列積を返す関数としてください。

行列積を計算する場合は、問題3の計算を異なる行や列に対して繰り返していくことになります。

計算結果である3×3の行列Cの各要素$c_{i,j}$は数式で表すと次のようになります。
$$
c_{i,j}=\sum_{ k = 0 }^{ 2 } a_{i,k}b_{k,j}
$$

In [124]:
def matrix_product(a, b):
    
    
    ans = np.zeros((a.shape))
    
    for i in range(a.shape[0]):
        for j in range(b.shape[1]):
            ans[i, j] = (a[i, :]*b[:, j]).sum()
            
    # 整数変換して出力
    return ans.astype(np.int64)

In [125]:
matrix_product(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

# 【問題5】計算が定義されない入力を判定する
問題4で作成した関数は、実装方法によってはこのDとEの配列を入力しても動いてしまう可能性があります。この場合、不適切な計算が行われることになります。また、途中でエラーになる場合でも、なぜエラーになったかが直接的には分かりづらいメッセージが表示されます。

if文などによってこれを防ぎ、入力される形に問題があることをprint()を使い表示するコードを書き加えてください。

In [126]:
def matrix_product_fix(a, b):
    
    
    ans = np.zeros((a.shape[0], b.shape[1]))
    
    
    if a.shape[1] != b.shape[0]:
        print('入力される形に問題があります。')
    
    else:        
        for i in range(a.shape[0]):
            for j in range(b.shape[1]):
                ans[i, j] = (a[i, :]*b[:, j]).sum()
            
        # 整数変換して出力
        return ans.astype(np.int64)

In [127]:
matrix_product_fix(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [128]:
# 入力に問題がある場合の例
d = np.array([[-1, 2, 3], [4, -5, 6]])
e = np.array([[-9, 8, 7], [6, -5, 4]])
matrix_product_fix(d, e)

入力される形に問題があります。


# 【問題6】転置
片方の行列を転置することで、行列積が計算できるようになります。

np.transpose()や.Tアトリビュートを用いて転置し、行列積を計算してください。

In [129]:
matrix_product_fix(d, e.T)

array([[ 46,  -4],
       [-34,  73]])